openapi: 3.0.1
info:
  contact:
    email: support@kanthorlabs.com
    name: Kanthor Support
    url: http://kanthorlabs.com/support
  description: SDK API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://kanthorlabs.com/terms/
  title: Kanthor SDK API
  version: "1.0"
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
servers:
- url: /api
paths:
  /account/me:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountGetRes'
          description: OK
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gateway.Error'
          description: ""
      security:
      - Authorization: []
      tags:
      - account
  /application:
    get:
      parameters:
      - description: list by ids
        explode: false
        in: query
        name: id
        schema:
          items:
            type: string
          type: array
        style: form
      - description: search keyword
        in: query
        name: _q
        schema:
          type: string
      - description: limit returning records
        in: query
        name: _limit
        schema:
          default: 10
          type: integer
      - description: current requesting page
        in: query
        name: _page
        schema:
          default: 0
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationListRes'
          description: OK
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gateway.Error'
          description: ""
      security:
      - Authorization: []
      - WorkspaceId: []
      tags:
      - application
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApplicationCreateReq'
        description: application payload
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationCreateRes'
          description: Created
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gateway.Error'
          description: ""
      security:
      - Authorization: []
      - WorkspaceId: []
      tags:
      - application
      x-codegen-request-body-name: payload
  /application/{app_id}:
    delete:
      parameters:
      - description: application id
        in: path
        name: app_id
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationDeleteRes'
          description: OK
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gateway.Error'
          description: ""
      security:
      - Authorization: []
      - WorkspaceId: []
      tags:
      - application
    get:
      parameters:
      - description: application id
        in: path
        name: app_id
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationGetRes'
          description: OK
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gateway.Error'
          description: ""
      security:
      - Authorization: []
      - WorkspaceId: []
      tags:
      - application
    patch:
      parameters:
      - description: application id
        in: path
        name: app_id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApplicationUpdateReq'
        description: application payload
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationUpdateRes'
          description: OK
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gateway.Error'
          description: ""
      security:
      - Authorization: []
      - WorkspaceId: []
      tags:
      - application
      x-codegen-request-body-name: payload
  /endpoint:
    get:
      parameters:
      - description: application id
        in: query
        name: app_id
        schema:
          type: string
      - description: list by ids
        explode: false
        in: query
        name: id
        schema:
          items:
            type: string
          type: array
        style: form
      - description: search keyword
        in: query
        name: _q
        schema:
          type: string
      - description: limit returning records
        in: query
        name: _limit
        schema:
          default: 10
          type: integer
      - description: current requesting page
        in: query
        name: _page
        schema:
          default: 0
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EndpointListRes'
          description: OK
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gateway.Error'
          description: ""
      security:
      - Authorization: []
      - WorkspaceId: []
      tags:
      - endpoint
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndpointCreateReq'
        description: endpoint payload
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EndpointCreateRes'
          description: Created
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gateway.Error'
          description: ""
      security:
      - Authorization: []
      - WorkspaceId: []
      tags:
      - endpoint
      x-codegen-request-body-name: payload
  /endpoint/{ep_id}:
    delete:
      parameters:
      - description: endpoint id
        in: path
        name: ep_id
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EndpointDeleteRes'
          description: OK
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gateway.Error'
          description: ""
      security:
      - Authorization: []
      - WorkspaceId: []
      tags:
      - endpoint
    get:
      parameters:
      - description: application id
        in: query
        name: app_id
        required: true
        schema:
          type: string
      - description: endpoint id
        in: path
        name: ep_id
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EndpointGetRes'
          description: OK
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gateway.Error'
          description: ""
      security:
      - Authorization: []
      - WorkspaceId: []
      tags:
      - endpoint
    patch:
      parameters:
      - description: endpoint id
        in: path
        name: ep_id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndpointUpdateReq'
        description: endpoint payload
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EndpointUpdateRes'
          description: OK
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gateway.Error'
          description: ""
      security:
      - Authorization: []
      - WorkspaceId: []
      tags:
      - endpoint
      x-codegen-request-body-name: payload
  /message:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageCreateReq'
        description: message payload
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageCreateRes'
          description: Created
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gateway.Error'
          description: ""
      security:
      - Authorization: []
      - WorkspaceId: []
      tags:
      - message
      x-codegen-request-body-name: payload
  /rule:
    get:
      parameters:
      - description: application id
        in: query
        name: app_id
        schema:
          type: string
      - description: endpoint id
        in: query
        name: ep_id
        schema:
          type: string
      - description: list by ids
        explode: false
        in: query
        name: id
        schema:
          items:
            type: string
          type: array
        style: form
      - description: search keyword
        in: query
        name: _q
        schema:
          type: string
      - description: limit returning records
        in: query
        name: _limit
        schema:
          default: 10
          type: integer
      - description: current requesting page
        in: query
        name: _page
        schema:
          default: 0
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EndpointRuleListRes'
          description: OK
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gateway.Error'
          description: ""
      security:
      - Authorization: []
      - WorkspaceId: []
      tags:
      - endpoint rule
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndpointRuleCreateReq'
        description: rule payload
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EndpointRuleCreateRes'
          description: Created
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gateway.Error'
          description: ""
      security:
      - Authorization: []
      - WorkspaceId: []
      tags:
      - endpoint rule
      x-codegen-request-body-name: payload
  /rule/{epr_id}:
    delete:
      parameters:
      - description: rule id
        in: path
        name: epr_id
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EndpointRuleDeleteRes'
          description: OK
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gateway.Error'
          description: ""
      security:
      - Authorization: []
      - WorkspaceId: []
      tags:
      - endpoint rule
    get:
      parameters:
      - description: rule id
        in: path
        name: epr_id
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EndpointRuleGetRes'
          description: OK
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gateway.Error'
          description: ""
      security:
      - Authorization: []
      - WorkspaceId: []
      tags:
      - endpoint rule
    patch:
      parameters:
      - description: rule id
        in: path
        name: epr_id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EndpointRuleUpdateReq'
        description: rule payload
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EndpointRuleUpdateRes'
          description: OK
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gateway.Error'
          description: ""
      security:
      - Authorization: []
      - WorkspaceId: []
      tags:
      - endpoint rule
      x-codegen-request-body-name: payload
components:
  schemas:
    AccountGetRes:
      example:
        account:
          sub: sub
          metadata:
            key: metadata
          name: name
      properties:
        account:
          $ref: '#/components/schemas/authenticator.Account'
      type: object
    Application:
      example:
        updated_at: 1
        name: name
        created_at: 6
        id: id
        ws_id: ws_id
      properties:
        created_at:
          type: integer
        id:
          type: string
        name:
          type: string
        updated_at:
          type: integer
        ws_id:
          type: string
      type: object
    ApplicationCreateReq:
      example:
        name: name
      properties:
        name:
          type: string
      type: object
    ApplicationCreateRes:
      example:
        updated_at: 6
        name: name
        created_at: 0
        id: id
        ws_id: ws_id
      properties:
        created_at:
          type: integer
        id:
          type: string
        name:
          type: string
        updated_at:
          type: integer
        ws_id:
          type: string
      type: object
    ApplicationDeleteRes:
      example:
        updated_at: 6
        name: name
        created_at: 0
        id: id
        ws_id: ws_id
      properties:
        created_at:
          type: integer
        id:
          type: string
        name:
          type: string
        updated_at:
          type: integer
        ws_id:
          type: string
      type: object
    ApplicationGetRes:
      example:
        updated_at: 6
        name: name
        created_at: 0
        id: id
        ws_id: ws_id
      properties:
        created_at:
          type: integer
        id:
          type: string
        name:
          type: string
        updated_at:
          type: integer
        ws_id:
          type: string
      type: object
    ApplicationListRes:
      example:
        data:
        - updated_at: 1
          name: name
          created_at: 6
          id: id
          ws_id: ws_id
        - updated_at: 1
          name: name
          created_at: 6
          id: id
          ws_id: ws_id
        count: 0
      properties:
        count:
          type: integer
        data:
          items:
            $ref: '#/components/schemas/Application'
          type: array
      type: object
    ApplicationUpdateReq:
      example:
        name: name
      properties:
        name:
          type: string
      type: object
    ApplicationUpdateRes:
      example:
        updated_at: 6
        name: name
        created_at: 0
        id: id
        ws_id: ws_id
      properties:
        created_at:
          type: integer
        id:
          type: string
        name:
          type: string
        updated_at:
          type: integer
        ws_id:
          type: string
      type: object
    Endpoint:
      example:
        method: method
        updated_at: 1
        name: name
        created_at: 6
        id: id
        app_id: app_id
        uri: uri
      properties:
        app_id:
          type: string
        created_at:
          type: integer
        id:
          type: string
        method:
          type: string
        name:
          type: string
        updated_at:
          type: integer
        uri:
          type: string
      type: object
    EndpointCreateReq:
      example:
        method: POST
        name: name
        app_id: app_id
        uri: https://example.com
      properties:
        app_id:
          type: string
        method:
          example: POST
          type: string
        name:
          type: string
        uri:
          example: https://example.com
          type: string
      type: object
    EndpointCreateRes:
      example:
        method: method
        updated_at: 6
        name: name
        created_at: 0
        id: id
        app_id: app_id
        uri: uri
      properties:
        app_id:
          type: string
        created_at:
          type: integer
        id:
          type: string
        method:
          type: string
        name:
          type: string
        updated_at:
          type: integer
        uri:
          type: string
      type: object
    EndpointDeleteRes:
      example:
        method: method
        updated_at: 6
        name: name
        created_at: 0
        id: id
        app_id: app_id
        uri: uri
      properties:
        app_id:
          type: string
        created_at:
          type: integer
        id:
          type: string
        method:
          type: string
        name:
          type: string
        updated_at:
          type: integer
        uri:
          type: string
      type: object
    EndpointGetRes:
      example:
        method: method
        updated_at: 6
        name: name
        created_at: 0
        id: id
        app_id: app_id
        uri: uri
      properties:
        app_id:
          type: string
        created_at:
          type: integer
        id:
          type: string
        method:
          type: string
        name:
          type: string
        updated_at:
          type: integer
        uri:
          type: string
      type: object
    EndpointListRes:
      example:
        data:
        - method: method
          updated_at: 1
          name: name
          created_at: 6
          id: id
          app_id: app_id
          uri: uri
        - method: method
          updated_at: 1
          name: name
          created_at: 6
          id: id
          app_id: app_id
          uri: uri
        count: 0
      properties:
        count:
          type: integer
        data:
          items:
            $ref: '#/components/schemas/Endpoint'
          type: array
      type: object
    EndpointRule:
      example:
        updated_at: 5
        exclusionary: true
        name: name
        created_at: 6
        condition_expression: condition_expression
        id: id
        ep_id: ep_id
        priority: 1
        condition_source: condition_source
      properties:
        condition_expression:
          type: string
        condition_source:
          type: string
        created_at:
          type: integer
        ep_id:
          type: string
        exclusionary:
          type: boolean
        id:
          type: string
        name:
          type: string
        priority:
          type: integer
        updated_at:
          type: integer
      type: object
    EndpointRuleCreateReq:
      example:
        exclusionary: true
        name: name
        condition_expression: condition_expression
        ep_id: ep_id
        priority: 0
        condition_source: condition_source
      properties:
        condition_expression:
          type: string
        condition_source:
          type: string
        ep_id:
          type: string
        exclusionary:
          type: boolean
        name:
          type: string
        priority:
          type: integer
      type: object
    EndpointRuleCreateRes:
      example:
        updated_at: 1
        exclusionary: true
        name: name
        created_at: 0
        condition_expression: condition_expression
        id: id
        ep_id: ep_id
        priority: 6
        condition_source: condition_source
      properties:
        condition_expression:
          type: string
        condition_source:
          type: string
        created_at:
          type: integer
        ep_id:
          type: string
        exclusionary:
          type: boolean
        id:
          type: string
        name:
          type: string
        priority:
          type: integer
        updated_at:
          type: integer
      type: object
    EndpointRuleDeleteRes:
      example:
        updated_at: 1
        exclusionary: true
        name: name
        created_at: 0
        condition_expression: condition_expression
        id: id
        ep_id: ep_id
        priority: 6
        condition_source: condition_source
      properties:
        condition_expression:
          type: string
        condition_source:
          type: string
        created_at:
          type: integer
        ep_id:
          type: string
        exclusionary:
          type: boolean
        id:
          type: string
        name:
          type: string
        priority:
          type: integer
        updated_at:
          type: integer
      type: object
    EndpointRuleGetRes:
      example:
        updated_at: 1
        exclusionary: true
        name: name
        created_at: 0
        condition_expression: condition_expression
        id: id
        ep_id: ep_id
        priority: 6
        condition_source: condition_source
      properties:
        condition_expression:
          type: string
        condition_source:
          type: string
        created_at:
          type: integer
        ep_id:
          type: string
        exclusionary:
          type: boolean
        id:
          type: string
        name:
          type: string
        priority:
          type: integer
        updated_at:
          type: integer
      type: object
    EndpointRuleListRes:
      example:
        data:
        - updated_at: 5
          exclusionary: true
          name: name
          created_at: 6
          condition_expression: condition_expression
          id: id
          ep_id: ep_id
          priority: 1
          condition_source: condition_source
        - updated_at: 5
          exclusionary: true
          name: name
          created_at: 6
          condition_expression: condition_expression
          id: id
          ep_id: ep_id
          priority: 1
          condition_source: condition_source
        count: 0
      properties:
        count:
          type: integer
        data:
          items:
            $ref: '#/components/schemas/EndpointRule'
          type: array
      type: object
    EndpointRuleUpdateReq:
      example:
        exclusionary: true
        name: name
        condition_expression: condition_expression
        priority: 0
        condition_source: condition_source
      properties:
        condition_expression:
          type: string
        condition_source:
          type: string
        exclusionary:
          type: boolean
        name:
          type: string
        priority:
          type: integer
      type: object
    EndpointRuleUpdateRes:
      example:
        updated_at: 1
        exclusionary: true
        name: name
        created_at: 0
        condition_expression: condition_expression
        id: id
        ep_id: ep_id
        priority: 6
        condition_source: condition_source
      properties:
        condition_expression:
          type: string
        condition_source:
          type: string
        created_at:
          type: integer
        ep_id:
          type: string
        exclusionary:
          type: boolean
        id:
          type: string
        name:
          type: string
        priority:
          type: integer
        updated_at:
          type: integer
      type: object
    EndpointUpdateReq:
      example:
        method: method
        name: name
      properties:
        method:
          type: string
        name:
          type: string
      type: object
    EndpointUpdateRes:
      example:
        method: method
        updated_at: 6
        name: name
        created_at: 0
        id: id
        app_id: app_id
        uri: uri
      properties:
        app_id:
          type: string
        created_at:
          type: integer
        id:
          type: string
        method:
          type: string
        name:
          type: string
        updated_at:
          type: integer
        uri:
          type: string
      type: object
    MessageCreateReq:
      example:
        headers:
          key: headers
        body:
          key: ""
        type: testing.debug
        app_id: app_id
      properties:
        app_id:
          type: string
        body:
          additionalProperties: true
          type: object
        headers:
          additionalProperties:
            type: string
          type: object
        type:
          example: testing.debug
          type: string
      type: object
    MessageCreateRes:
      example:
        id: id
      properties:
        id:
          type: string
      type: object
    authenticator.Account:
      example:
        sub: sub
        metadata:
          key: metadata
        name: name
      properties:
        metadata:
          additionalProperties:
            type: string
          type: object
        name:
          type: string
        sub:
          type: string
      type: object
    gateway.Error:
      properties:
        code:
          type: string
        error:
          type: string
      type: object
  securitySchemes:
    Authorization:
      description: "[Bearer JWT_TOKEN] or [Basic base64(key:secret)]"
      in: header
      name: Authorization
      type: apiKey
    WorkspaceId:
      description: The selected workspace id you are working with
      in: header
      name: x-authorization-workspace
      type: apiKey
x-original-swagger-version: "2.0"
